version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Installing node modules
          command: npm install
      - run:
          name: Install JUnit coverage reporter
          command: npm install --save-dev jest-junit
      - checkout
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_artifacts:
          path: coverage